### ISSUE TITLE
Use ViewPlaceholder at the main page

### ISSUE THREAD

**Issue by mentaljam** [beidl/ISODrive#3]
The [noFileHint](https://github.com/beidl/ISODrive/blob/master/qml/pages/MainPage.qml#L74-L80) label on the main page could be replaced with the [ViewPlaceholder](https://sailfishos.org/develop/docs/silica/qml-sailfishsilica-sailfish-silica-viewplaceholder.html/) that would be more "Silicable".

**Comment by Wedmer** [comment]
I think it should be closed.
