### ISSUE TITLE
Does not start on SailfishOS 4.5

### ISSUE THREAD

**Issue by citronalco** [beidl/ISODrive#9]
Error:
```
[W] unknown:8 - file:///usr/share/ISODrive/qml/ISODrive.qml:8:30: Type MainPage unavailable 
         initialPage: Component { MainPage { } } 
                                  ^
[W] unknown:3 - file:///usr/share/ISODrive/qml/pages/MainPage.qml:3:1: module "QtSparql" is not installed 
     import QtSparql 1.0 
     ^
```

**Comment by fredldotme** [comment]
Haven't had contact with SailfishOS for a long time but it seems either a system component that used to be shipped in the OS is not there anymore, or the version has changed.

Maybe this can be fixed by shipping the QtSparql module as part of the rpm.
